services:
  redis:
    image: redis/redis-stack:7.2.0-v7
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - /srv/data/redis:/data
    networks:
      - central-data-platform
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  central-data-platform:
    external: true